
# Prefix
set-option -g prefix C-a
bind-key C-a last-pane
bind-key a send-prefix

# Splits
bind-key v split-window -h
bind-key b split-window

# Window/pane numbering
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# Titles
set-option -g set-titles on
set-option -g allow-rename on
set-window-option -g automatic-rename off

# Performance
set -s escape-time 0
setw -g aggressive-resize on

# Activity
setw -g monitor-activity on
set -g visual-activity on

# Vi copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# hjkl pane navigation
bind h select-pane -L \; display-pane
bind j select-pane -D \; display-pane
bind k select-pane -U \; display-pane
bind l select-pane -R \; display-pane

# Pane resize
bind Up    resize-pane -U 5
bind Down  resize-pane -D 5
bind Left  resize-pane -L 5
bind Right resize-pane -R 5

# Layouts
bind m set-window-option main-pane-height 60\; select-layout main-horizontal
bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# Sessionizer
bind-key -r f run-shell "tmux neww ~/bin/tmux-sessionizer"

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Display
set -g display-panes-time 2000

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin '2KAbhishek/tmux2k'

# tmux2k config
set -g @tmux2k-theme 'catppuccin'
set -g @tmux2k-left-plugins "git cpu ram"
set -g @tmux2k-right-plugins "battery network time"
set -g @tmux2k-start-icon ""

# Initialize TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
